export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_START = "AUTH_LOGIN_START";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_START = "AUTH_REGISTER_START";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";

export const CHECK_AUTH = "CHECK_AUTH";

export const UPDATE_PROFILE_PICTURE = "UPDATE_PROFILE_PICTURE";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
