export const FETCH_PROFILE = "FETCH_PROFILE";
export const FETCH_PROFILE_ERROR = "FETCH_PROFILE_ERROR";
export const FETCH_PROFILE_START = "FETCH_PROFILE_START";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCES";
