export const FETCH_PROFILE: string = "FETCH_PROFILE";
export const FETCH_PROFILE_ERROR: string = "FETCH_PROFILE_ERROR";
export const FETCH_PROFILE_START: string = "FETCH_PROFILE_START";
export const FETCH_PROFILE_SUCCESS: string = "FETCH_PROFILE_SUCCESS";
