export const ADD_TRACK = "ADD_TRACK";
export const ADD_TRACK_ERROR = "ADD_TRACK_ERROR";
export const ADD_TRACK_START = "ADD_TRACK_START";
export const ADD_TRACK_SUCCESS = "ADD_TRACK_SUCCESS";

export const CLEAR_TRACK_ERROR = "CLEAR_TRACK_ERROR";
export const CLEAR_TRACK_LOADING = "CLEAR_TRACK_LOADING";

export const DELETE_TRACK = "DELETE_TRACK";
export const DELETE_TRACK_ERROR = "DELETE_TRACK_ERROR";
export const DELETE_TRACK_START = "DELETE_TRACK_START";
export const DELETE_TRACK_SUCCESS = "DELETE_TRACK_SUCCESS";

export const FETCH_TRACK = "FETCH_TRACK";
export const FETCH_TRACK_ERROR = "FETCH_TRACK_ERROR";
export const FETCH_TRACK_START = "FETCH_TRACK_START";
export const FETCH_TRACK_SUCCESS = "FETCH_TRACK_SUCCESS";

export const UPDATE_TRACK = " UPDATE_TRACK";
export const UPDATE_TRACK_ERROR = " UPDATE_TRACK_ERROR";
export const UPDATE_TRACK_START = " UPDATE_TRACK_START";
export const UPDATE_TRACK_SUCCESS = " UPDATE_TRACK_SUCCESS";
