export const ADD_TRACK = "ADD_TRACK";
export const ADD_TRACK_SUCCESS = "ADD_TRACK_SUCCESS";

export const FETCH_TRACK = "FETCH_TRACK";
export const FETCH_TRACK_SUCCESS = "FETCH_TRACK_SUCCESS";

export const DELETE_TRACK = "DELETE_TRACK";
