export const ADD_TRACK = "ADD_TRACK";
export const ADD_TRACK_START = "ADD_TRACK_START";
export const ADD_TRACK_SUCCESS = "ADD_TRACK_SUCCESS";

export const CLEAR_TRACK_LOADING = "CLEAR_TRACK_LOADING";

export const FETCH_TRACK = "FETCH_TRACK";
export const FETCH_TRACK_START = "FETCH_TRACK_START";
export const FETCH_TRACK_SUCCESS = "FETCH_TRACK_SUCCESS";

export const DELETE_TRACK = "DELETE_TRACK";
export const DELETE_TRACK_START = "DELETE_TRACK_START";
export const DELETE_TRACK_SUCCESS = "DELETE_TRACK_SUCCESS";
